---
- name: Dotfiles
  hosts: local
  tasks:
    # NOTE: https://brew.sh/
    - name: Install Homebrew
      ansible.builtin.command: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      args:
        creates: /opt/homebrew/bin/brew
      tags:
        - brew

    - name: Update Homebrew
      community.general.homebrew:
        update_homebrew: true
      tags:
        - brew

    - name: Install Brew packages
      community.general.homebrew:
        name:
          - asdf
          - awscli
          - bash-language-server
          - bat
          - bfs
          - bottom
          - buildkit
          - ca-certificates
          - colima
          - curlie
          - docker
          - docker-buildx
          - docker-completion
          - docker-compose
          - dog
          - eza
          - flux
          - gh
          - git
          - gitops
          - git-delta
          - git-open
          - hadolint
          - helix
          - helm
          - htop
          - jq
          - jump
          - k9s
          - minikube
          - neovim
          - node
          - nova
          - oath-toolkit
          - parallel
          # - pkgx
          - qemu
          - redis
          - ripgrep
          - safe-rm
          - shellcheck
          - sops
          - telia-oss/tap/aws-env
          - terminal-notifier
          - terraform-ls
          - tree
          - tree-sitter
          - vivid
          - watch
          - wget
          - zoxide
      tags:
        - brew

    - name: Install Brew Casks
      community.general.homebrew_cask:
        name:
          - dozer
          - finch
          - maccy
          - openlens
      tags:
        - brew

    - name: Create directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - ~/.config
        - ~/.config/nvim
        - ~/.docker
        - ~/.docker/cli-plugins
        - ~/.zinit

    - name: Create symlinks
      ansible.builtin.file:
        path: "{{ item.dest }}"
        src: "{{ item.src }}"
        state: link
      loop:
        - { src: ~/dotfiles/.gitconfig, dest: ~/.gitconfig }
        - { src: ~/dotfiles/.gitignore_global, dest: ~/.gitignore_global }
        - { src: ~/dotfiles/.p10k.zsh, dest: ~/.p10k.zsh }
        - { src: ~/dotfiles/.vimrc, dest: ~/.vimrc }
        - { src: ~/dotfiles/.zshrc, dest: ~/.zshrc }
        - { src: ~/dotfiles/init.vim, dest: ~/.config/nvim/init.vim }
        - src: /opt/homebrew/opt/docker-compose/bin/docker-compose
          dest: ~/.docker/cli-plugins/docker-compose
      notify:
        - Compile zinit

    - name: Clone zinit
      ansible.builtin.git:
        repo: git@github.com:zdharma-continuum/zinit.git
        dest: ~/.zinit/bin
        update: true
        # noqa: latest
        version: HEAD
      notify:
        - Compile zinit source
      tags:
        - zinit

# TODO: Krew
  handlers:
    - name: Compile zinit source
      # noqa: no-changed-when
      ansible.builtin.command:
        cmd: zsh -c 'zcompile ~/.zinit/bin/zinit.zsh'

    - name: Compile zinit
      # noqa: no-changed-when
      ansible.builtin.command:
        cmd: zsh -c 'zinit compile --all'
