---
# tasks file for homebrew

# NOTE: https://brew.sh/
- name: Install Homebrew
  ansible.builtin.command: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  args:
    creates: /opt/homebrew/bin/brew

- name: Update Homebrew
  community.general.homebrew:
    update_homebrew: true

- name: Install Brew packages
  community.general.homebrew:
    name: "{{ packages }}"

- name: Install Brew Casks
  community.general.homebrew_cask:
    name: "{{ casks }}"

- name: Create Docker plugin dir
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  loop:
    - ~/.docker
    - ~/.docker/cli-plugins

- name: Create Docker plugin links
  ansible.builtin.file:
    path: "{{ item.dest }}"
    src: "{{ item.src }}"
    state: link
  loop:
    - src: /opt/homebrew/opt/docker-compose/bin/docker-compose
      dest: ~/.docker/cli-plugins/docker-compose
    - src: /opt/homebrew/opt/docker-buildx/bin/docker-buildx
      dest: ~/.docker/cli-plugins/docker-buildx
