---
# tasks file for krew
- name: Unarchive Krew
  ansible.builtin.unarchive:
    src: https://github.com/kubernetes-sigs/krew/releases/latest/download/krew-{{ ansible_facts.os_family | lower }}_{{ ansible_facts.architecture }}.tar.gz
    dest: ~/.krew
    remote_src: true

- name: Install Krew
  ansible.builtin.shell: ./krew-{{ ansible_facts.os_family | lower }}_{{ ansible_facts.architecture }} install krew && touch .installed
  args:
    chdir: ~/.krew
    creates: ~/.krew/.installed

- name: Install Krew plugins
  ansible.builtin.shell: kubectl krew install {{ item }} && touch .{{ item }}.installed
  args:
    chdir: ~/.krew
    creates: ~/.krew/.{{ item }}.installed
  loop: "{{ plugins }}"
